ENV["VAGRANT_EXPERIMENTAL"] = "disks"
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/focal64"

  config.vm.disk :disk, size: "300MB", name: "disk_1"
  config.vm.disk :disk, size: "300MB", name: "disk_2"
  config.vm.disk :disk, size: "300MB", name: "disk_3"
  config.vm.disk :disk, size: "300MB", name: "disk_4"

  config.vm.provision "shell", path: "script.sh"
end